export const AUTH_LOGIN = "AUTH_LOGIN";
export const AUTH_LOGIN_LOADED = "AUTH_LOGIN_LOADED";
export const AUTH_SIGNUP = "AUTH_SIGNUP";
export const AUTH_SIGNUP_LOADED = "AUTH_SIGNUP_LOADED";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const AUTH_LOGOUT_LOADED = "AUTH_LOGOUT_LOADED";
export const UPLOAD_AVATAR = "UPLOAD_AVATAR";
export const UPLOAD_AVATAR_LOADED = "UPLOAD_AVATAR_LOADED";
