export const AUTH_LOGIN = "AUTH_LOGIN";
export const AUTH_LOGIN_LOADED = "AUTH_LOGIN_LOADED";
export const AUTH_SIGNUP = "AUTH_SIGNUP";
export const AUTH_SIGNUP_LOADED = "AUTH_SIGNUP_LOADED";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const AUTH_LOGOUT_LOADED = "AUTH_LOGOUT_LOADED";
export const UPLOAD_AVATAR = "UPLOAD_AVATAR";
export const UPLOAD_AVATAR_LOADED = "UPLOAD_AVATAR_LOADED";
export const DELETE_ACCOUNT = "DELETE_ACCOUNT";
export const DELETE_ACCOUNT_LOADED = "DELETE_ACCOUNT_LOADED";


export const CREATE_THREAD = "CREATE_THREAD"
export const CREATE_THREAD_LOADED = "CREATE_THREAD_LOADED"
export const GET_THREADS = "GET_THREADS";
export const GET_THREADS_LOADED = "GET_THREADS_LOADED";
export const SINGLE_THREAD = "SINGLE_THREAD";
export const POST_REPLY = "POST_REPLY";
export const POST_REPLY_LOADED = "POST_REPLY_LOADED";
export const GET_REPLY = "GET_REPLY";
export const GET_REPLY_LOADED = "GET_REPLY_LOADED";